spring:

  jpa:
    hibernate:
      ddl-auto: validate

#--------------------postgresql properties--------------------#
  datasource:
    username: 'postgres'
    password: 'password'
    url: 'jdbc:postgresql://localhost:5432/user-login'
    driver-class-name: org.postgresql.Driver

#--------------------flyway properties--------------------#
  flyway:
    baseline-on-migrate: true

#--------------------jwt token--------------------#
  jwt:
    secret: b64r9mCtI4x3aLkKjpM7K7Q6w7I6Z4pHxu1b8G8Hw2M9sV5fY3jR2uN1wW6tA0pP4oQ2vN5xY2zT8kI1gX3rF7yM2bT0oH1zR9a
    expired-time: 36000000

  #--------------------google auth2--------------------#
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: <client id>
            clientSecret: <client secret>
        provider:
          google:
            authorizationUri: https://accounts.google.com/o/oauth2/auth
            tokenUri: https://accounts.google.com/o/oauth2/token
            userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
