spring:

  jpa:
    hibernate:
      ddl-auto: validate

#--------------------postgresql properties--------------------#
  datasource:
    username: 'postgres'
    password: 'password'
    url: 'jdbc:postgresql://localhost:5432/user-login'
    driver-class-name: org.postgresql.Driver

#--------------------flyway properties--------------------#
  flyway:
    baseline-on-migrate: true
